# Generated by Django 3.1.7 on 2021-04-02 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210402_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Pin_Code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$')]),
        ),
    ]
